import type { CaseStudyVisual as Visual } from '@/src/data/case-studies'

function Caption({ visual }: { visual: Visual }) { return <div className="mt-4 grid gap-2 border-t border-border pt-3 sm:grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)] sm:items-start"><p className="break-words font-mono text-[10px] uppercase leading-relaxed tracking-[0.16em] text-accent">{visual.label}</p><p className="text-xs leading-relaxed text-muted-foreground sm:text-right">{visual.note}</p></div> }

export function CaseStudyVisual({ visual }: { visual: Visual }) {
  if (visual.mode === 'sim2real') return <div className="rounded-xl border border-border bg-card/55 p-5 sm:p-6"><div className="grid gap-4 sm:grid-cols-2">{[['Before adaptation','2.38%','2.38%'],['After adaptation','95.24%','95.24%']].map(([title,value,width],index) => <div key={title} className="rounded-lg border border-border bg-background/45 p-5"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-muted-foreground">{title}</p><p className={`mt-3 break-words font-heading text-[clamp(2.8rem,12vw,3.75rem)] leading-[0.95] tracking-tight ${index ? 'text-accent' : 'text-foreground'}`}>{value}</p><div className="mt-5 h-2 overflow-hidden rounded-full bg-secondary"><div className={`h-full rounded-full ${index ? 'bg-accent' : 'bg-muted-foreground/45'}`} style={{ width }} /></div></div>)}</div><Caption visual={visual} /></div>
  if (visual.mode === 'reliability') return <div className="rounded-xl border border-border bg-card/55 p-5 sm:p-6"><div className="grid gap-4 md:grid-cols-[0.9fr_1.1fr]"><div className="rounded-lg border border-border bg-background/45 p-5"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-accent">Synthetic invoice</p><div className="mt-5 space-y-3">{[['Provider','Example Vet'],['Invoice ID','INV-204'],['Total','$184.90'],['Tax','$16.81'],['Line items','04']].map(([a,b]) => <div key={a} className="flex justify-between gap-4 border-b border-border pb-2 text-xs"><span className="text-muted-foreground">{a}</span><span className="font-mono text-foreground">{b}</span></div>)}</div></div><div className="rounded-lg border border-border bg-background/45 p-5"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-accent">Extraction trace</p><div className="mt-5 space-y-3">{[['invoice_total','0.97','validated'],['provider_name','0.74','review'],['line_item_tax','0.42','mismatch']].map(([a,b,c]) => <div key={a} className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-2 rounded-md border border-border bg-card/55 px-3 py-2 text-xs sm:grid-cols-[minmax(0,1fr)_auto_auto] sm:gap-3"><span className="break-all font-mono text-muted-foreground">{a}</span><span>{b}</span><span className={`col-span-2 w-fit rounded-full border border-border px-2 py-0.5 font-mono text-[10px] uppercase tracking-[0.08em] sm:col-span-1 ${c === 'validated' ? 'text-emerald-300' : c === 'review' ? 'text-amber-300' : 'text-rose-300'}`}>{c}</span></div>)}</div></div></div><Caption visual={visual} /></div>
  if (visual.mode === 'retrieval') return <div className="rounded-xl border border-border bg-card/55 p-5 sm:p-6"><div className="grid gap-4 md:grid-cols-3">{[['Precision@5','0.68'],['Recall@5','0.68'],['Embedding size','384d']].map(([a,b]) => <div key={a} className="rounded-lg border border-border bg-background/45 p-5"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-muted-foreground">{a}</p><p className="mt-4 break-words font-heading text-[clamp(2.25rem,10vw,3rem)] leading-[0.96] tracking-tight text-accent">{b}</p></div>)}</div><Caption visual={visual} /></div>
  if (visual.mode === 'rl-system') return <div className="rounded-xl border border-border bg-card/55 p-5 sm:p-6"><div className="grid gap-3 md:grid-cols-4">{[['01','Observe','Frame skipping and frame stacking'],['02','Configure','Policy and reward design'],['03','Train','Benchmark environments'],['04','Evaluate','Endpoint metrics and success conditions']].map(([number,title,note]) => <div key={number} className="rounded-lg border border-border bg-background/45 p-4"><p className="font-mono text-[10px] text-accent">{number}</p><p className="mt-7 text-sm font-medium text-foreground">{title}</p><p className="mt-2 text-xs leading-relaxed text-muted-foreground">{note}</p></div>)}</div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-lg border border-border bg-background/45 p-4"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-accent">AirRaid PPO</p><p className="mt-3 font-heading text-3xl tracking-tight text-foreground">300 <span className="text-accent">→</span> 1,925</p><p className="mt-2 text-xs leading-relaxed text-muted-foreground">Verified mean-reward endpoints after temporal observation changes.</p></div><div className="rounded-lg border border-border bg-background/45 p-4"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-accent">MountainCar</p><p className="mt-3 font-heading text-3xl tracking-tight text-accent">100%</p><p className="mt-2 text-xs leading-relaxed text-muted-foreground">Final success rate under the shaped-reward evaluation.</p></div></div><Caption visual={visual} /></div>
  if (visual.mode === 'graph') return <div className="rounded-xl border border-border bg-card/55 p-5 sm:p-6"><div className="relative h-72 overflow-hidden rounded-lg border border-border bg-background/45 bg-grid"><svg viewBox="0 0 760 280" className="h-full w-full" role="img" aria-label="Conceptual temporal graph"><g stroke="currentColor" className="text-accent/25" strokeWidth="1.5"><path d="M88 148 L222 72 L352 144 L486 78 L650 142" /><path d="M88 148 L222 214 L352 144 L486 218 L650 142" /><path d="M222 72 L222 214" /><path d="M486 78 L486 218" /></g>{[[88,148,'t0'],[222,72,'t1'],[222,214,'t1'],[352,144,'t2'],[486,78,'t3'],[486,218,'t3'],[650,142,'fraud?']].map(([x,y,label]) => <g key={`${x}-${y}`}><circle cx={x as number} cy={y as number} r="18" className="fill-background stroke-accent/70" strokeWidth="2" /><text x={x as number} y={(y as number)+4} textAnchor="middle" className="fill-foreground text-[11px] font-mono">{label}</text></g>)}</svg></div><Caption visual={visual} /></div>

  if (visual.mode === 'ir') return <div className="rounded-xl border border-border bg-card/55 p-5 sm:p-6"><div className="grid gap-3 md:grid-cols-4">{[['01','Clean','Text preprocessing'],['02','Compare','TF-IDF baseline'],['03','Encode','Dense embeddings'],['04','Rank','Evaluate relevance']].map(([number,title,note]) => <div key={number} className="rounded-lg border border-border bg-background/45 p-4"><p className="font-mono text-[10px] text-accent">{number}</p><p className="mt-7 text-sm font-medium text-foreground">{title}</p><p className="mt-2 text-xs leading-relaxed text-muted-foreground">{note}</p></div>)}</div><Caption visual={visual} /></div>
  if (visual.mode === 'ml') return <div className="rounded-xl border border-border bg-card/55 p-5 sm:p-6"><div className="grid gap-3 md:grid-cols-4">{[['Data','Clean and explore'],['Features','Represent the problem'],['Compare','Benchmark models'],['Inspect','Analyse errors']].map(([title,note],index) => <div key={title} className="rounded-lg border border-border bg-background/45 p-4"><p className="font-mono text-[10px] text-accent">0{index + 1}</p><p className="mt-7 text-sm font-medium text-foreground">{title}</p><p className="mt-2 text-xs leading-relaxed text-muted-foreground">{note}</p></div>)}</div><Caption visual={visual} /></div>
  if (visual.mode === 'governance') return <div className="rounded-xl border border-border bg-card/55 p-5 sm:p-6"><div className="grid gap-3 md:grid-cols-4">{[['Risk','What can go wrong?'],['Evidence','What do we know?'],['Oversight','Who reviews decisions?'],['Govern','How is the system improved?']].map(([title,note],index) => <div key={title} className="rounded-lg border border-border bg-background/45 p-4"><p className="font-mono text-[10px] text-accent">0{index + 1}</p><p className="mt-7 text-sm font-medium text-foreground">{title}</p><p className="mt-2 text-xs leading-relaxed text-muted-foreground">{note}</p></div>)}</div><Caption visual={visual} /></div>

  return <div className="rounded-xl border border-border bg-card/55 p-5 sm:p-6"><div className="grid gap-3 md:grid-cols-4">{['Documents','Embeddings','Retrieval','Response'].map((item,index) => <div key={item} className="rounded-lg border border-border bg-background/45 p-4"><p className="font-mono text-[10px] text-accent">0{index + 1}</p><p className="mt-8 text-sm text-foreground">{item}</p></div>)}</div><Caption visual={visual} /></div>
}
